development:
  adapter: postgresql
  encoding: unicode
  database: openvisu_development
  pool: 5
  password:
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: openvisu_development
  pool: 5
  password:
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  password:
  template: template0